version: '3'

services:
  ldap-server:
    image: osixia/openldap:latest
    restart: always
    container_name: ldap-host
    environment:
      LDAP_ORGANISATION: "kfc"
      LDAP_DOMAIN: "kfc.local"
      LDAP_ADMIN_PASSWORD: "abcd1234L#"
    ports:
      - "389:389"
    networks:
      - webnet
    volumes:
      - "/home/huimin/ldap/persistent/ldap:/var/lib/ldap"
      - "/home/huimin/ldap/persistent/slapd.d:/etc/ldap/slapd.d"

  ldap-admin:
    image: osixia/phpldapadmin:latest
    restart: always
    container_name: ldap-admin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    links:
      - "ldap-server:ldap"
    networks:
      - webnet

networks:
  webnet:
